Optimize Memory Handling in Embedding Computations and Refactor EmbeddingService
sacdallago/biotrainer pull request #103
Opened 2024-08-16 13:03 UTC by heispv

### **Description:**
This PR enhances the `EmbeddingService` by optimizing memory usage during embedding computations, refactoring core logic, and adding unit tests for robustness.

### **Key Changes:**
1. **Dynamic Memory Management:**
   - Automatically estimate and manage RAM usage by saving embeddings to disk when memory limits are reached.

2. **Refactor `EmbeddingService`:**
   - Extracted core logic into a dedicated method.
   - Handled ultra-long reads by saving embeddings immediately and preventing additional sequence loading.
   - Removed `SAVE_AFTER_N_EMBEDDINGS`.

3. **Unit Testing:**
   - Added tests for computing embeddings on long, short, and mixed sequences.
   - Validated dynamic memory management and embedding computation accuracy.
   - Ensured correct result paths and file existence in the tests.

### **Issue Reference:**
Fixes [#98]

2024-08-19 09:02 UTC, SebieF requested changes
Very nice work, thank you for looking into this quite complex problem! :)

Most of my comments are minor suggestions for improvements, the only major change that I would suggest is to unify the handling of the ultra-long reads and normal reads if at all possible, and removing the while loops altogether. 

Other than that, the approach seems to work fine, I ran the tests locally and executed a run with ProtT5 for 2377 sequences successfully.

2024-08-25 10:59 UTC, heispv commented
Thank you for the suggestions on improving the changes I made. I just updated the code based on your feedback! :)

2024-08-25 14:46 UTC, SebieF requested changes
Thanks, the embedding calculation is much easier to understand now with your solution to use only one loop! :+1:  

I only have a few small suggestions left, then we are ready to rebase. :smile:

2024-08-25 14:46 UTC, SebieF commented on biotrainer/embedders/embedding_service.py
> +        with tqdm(total=total_sequences, initial=1, desc="Processing Sequences") as pbar:
I just checked locally, and the processing bar is not shown yet for the first embedding calculation. Could you move the whole line to line 108, then it should be shown. You have to double check if the initial value is still correct (0 or 1?) and probably have to call `pbar.update(1)` once manually after the line 108. But I think the improved user feedback is worth this small overhead.

Additionally, I would suggest to use `desc="Computing embeddings"` to be clearer about the description (but adding the description is a good idea anyway, thanks!)

2024-08-25 14:46 UTC, SebieF commented on biotrainer/embedders/embedding_service.py
>          gc.collect()
Sorry I think I did not express myself well here, please add the `del self._embedder` statement here and remove the `gc.collect()` call from line 81, such that the embedding model is deleted, but the garbage collector is only called once.

Lines 148-150 should look like this then:
```python
        del embeddings 
        del self._embedder
        gc.collect()
```

2024-08-25 14:46 UTC, SebieF commented on biotrainer/embedders/embedding_service.py
> +        Calculates the maximum number of embeddings that can fit in available memory.
Please add an explanation to the doc string how you found the magic constants in this function (`0.75` and `18`) and how they can be interpreted

2024-08-25 14:46 UTC, SebieF commented on tests/test_embedding_service.py
> +        if os.environ.get('CI') == 'true':
Nice solution, and seems to work as the tests took about 11mins. Did you double check that it works in the CI pipeline though? Might be nice to put a logging statement here to be able to make it easier understandable in the pipeline, why the test takes so long (for new developers for example).

2024-08-26 09:50 UTC, heispv commented
Sebastian, I just updated the code as you suggested 😉

2024-08-26 09:57 UTC, SebieF approved these changes
Thank you very much! :)

2024-08-26 10:19 UTC, merged